### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by savioreagle** [smoneck/m3u2volumio#3]
sorry for my english but several hours i try to run the script but impossible
`volumio@mutfak:~$ m3u2volumio test.m3u
-bash: m3u2volumio: command not found
`
Can u help me please

**Comment by robin-morand** [comment]
Hi 
You can try: chmod +x m3u2volumio.py

Also try to add python at the begining of the command : python m3u2volumino ....

Chmod +x change the file permission to allow eXecution

**Comment by suuuehgi** [comment]
By executing

```bash
volumio@mutfak:~$ m3u2volumio test.m3u
```
within you shell, you implicitly query the `PATH` variable whether `m3u2volumio` is present on the locations the variable holds. Have a look:

```bash
$ echo $PATH
/usr/sbin:/usr/bin:/sbin:/bin
```
If its neither in `/usr/sbin`, nor `/usr/bin`, nor `/sbin` or `/bin`, you get `command not found`.

Since its a python script, you can either call it directly via

```bash
python3 /path/to/m3u2volumio.py [...]
```

or execute it directly

```bash
/path/to/m3u2volumio.py [...]
```

if you declared it to be executable beforehand:

```bash
chmod +x m3u2volumio.py
```
This implicitly executes the program given on the first line `#!/usr/bin/python3` (see [Shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))) that then runs the script.
